import { defineConfig, devices } from "@playwright/test";
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.resolve(__dirname, ".env") });

// Defines and exports the Playwright test configuration.
export default defineConfig({
  // The root directory where Playwright will look for test files.
  testDir: "./e2e/specs",

  // Run tests in files in parallel for maximum speed.
  fullyParallel: true,

  // Fail the build on CI if you accidentally left `test.only` in the source code.
  forbidOnly: !!process.env.CI,

  // Retry failed tests to reduce flakiness, especially in a CI environment.
  retries: process.env.CI ? 2 : 0,

  // The number of parallel worker processes.
  workers: process.env.CI ? 1 : 5,

  // Configures the reporters for test results.
  reporter: [
    // Generates a self-contained HTML report of the test run.
    ["html", { outputFolder: "e2e/playwright-report", open: "never" }],
    // Generates a JSON file with detailed test results, useful for custom reporting.
    ["json", { outputFile: "e2e/test-results/results.json" }],
    // On CI, use the GitHub Actions reporter for integrated annotations.
    process.env.CI ? ["github"] : ["list"],
  ],

  // The directory where test artifacts like screenshots, videos, and traces are stored.
  outputDir: "e2e/test-results",

  // Global settings for all test projects, defined in the `use` object.
  use: {
    // The base URL for all navigations (`page.goto('/')`), making tests environment-agnostic.
    baseURL: process.env.E2E_BASE_URL || "http://localhost:3000",

    // Record a trace for each test, but only on the first retry of a failed test.
    trace: "on-first-retry",

    // Capture screenshots automatically, but only when a test fails.
    screenshot: "only-on-failure",

    // Record videos of test runs, but only on the first retry of a failed test.
    video: "on-first-retry",

    // The default viewport size for all tests.
    viewport: { width: 1280, height: 720 },
  },

  // Global timeout for each test case, including all hooks.
  timeout: 120000, // 2 minutes
  // Timeout for individual expect assertions.
  expect: {
    timeout: 5000, // 5 seconds
  },

  // Path to a module that is executed once before all tests.
  globalSetup: "./e2e/utils/global-setup.ts",
  // Path to a module that is executed once after all tests.
  globalTeardown: "./e2e/utils/global-teardown.ts",

  // Defines different projects to run tests under various configurations.
  projects: [
    {
      // A special project dedicated to running the authentication setup file.
      name: "setup",
      testDir: "./e2e/utils",
      testMatch: /.*\.setup\.ts/,
    },
    {
      // A project for running tests that require an authenticated user on a desktop browser.
      name: "authenticated",
      use: {
        ...devices["Desktop Chrome"],
        // Uses the saved authentication state generated by the 'setup' project.
        storageState: "e2e/.auth/credential-user.json",
      },
      // This project depends on the 'setup' project completing successfully first.
      dependencies: ["setup"],
      // Ignores public and auth-related tests, as they are covered by the 'unauthenticated' project.
      testIgnore: ["**/public/**", "**/auth/**"],
    },
    {
      // A project for running tests for unauthenticated users on a desktop browser.
      name: "unauthenticated",
      use: {
        ...devices["Desktop Chrome"],
        // No `storageState` is used, so these tests run as a logged-out user.
      },
      // This project specifically targets tests in the 'public' and 'auth' directories.
      testMatch: ["**/public/**", "**/auth/**"],
    },
    {
      // A project for running tests that require an authenticated user on a mobile device.
      name: "mobile",
      use: {
        ...devices["Pixel 5"],
        storageState: "e2e/.auth/credential-user.json",
      },
      dependencies: ["setup"],
      // This project only runs test files that end with `.mobile.spec.ts`.
      testMatch: /.*\.mobile\.spec\.ts/,
    },
  ],

  // Configures the local development web server. Playwright will start this server before running tests.
  webServer: {
    // The command to start the development server.
    command: "pnpm dev",
    // The URL Playwright will poll to check if the server is ready.
    url: "http://localhost:3000",
    // On local machines, reuse an already running dev server for faster test runs.
    reuseExistingServer: !process.env.CI,
    // The maximum time to wait for the web server to start.
    timeout: 120000, // 2 minutes
  },
});
