import "@/app/globals.css";

import { Geist_Mono, Inter, Plus_Jakarta_Sans } from "next/font/google";
import { Metadata } from "next/types";

import QueryProvider from "@/components/providers/query-provider";
import { NextAuthSessionProvider } from "@/components/providers/session-provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MortiScope — Insect Hold the Clues",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${plusJakartaSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextAuthSessionProvider>
          <QueryProvider>
            <main>{children}</main>
            <Toaster position="bottom-right" richColors />
          </QueryProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
